### ISSUE TITLE
yahoo_finance.py issue with downloading stock data

### ISSUE THREAD

**Issue by kp7425** [ebranlard/mlstocks#1]
Hi ,

There was a recently update to yfinance anace query https://query1.finance.yahoo.com/ which is causing error while downloading the stock price, sector.

Error: json.decoder.jsondecodeerror expecting value line 1 column 1 (char 0) . I added a header section to data = requests.get(url=url, params=params,headers=headers) which resovled the json.decoder error issue. But sector and other details are not being downloaded as yfinance query might have changed.

**Comment by ebranlard** [comment]
Thank you for that, I'll try to fix it!

**Comment by kp7425** [comment]
Updating get_json function with header fixed the issue.

def get_json(url, proxy=None):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
    html = requests.get(url=url, proxies=proxy,headers=headers).text
    if "QuoteSummaryStore" not in html:
        raise EmptyDataException()

**Comment by kp7425** [comment]
header needed to be updated to fix the issue

**Comment by kp7425** [comment]
We can close the ticket. I saw your latest commit 2 months ago. I was using the older version in google colab

**Comment by ebranlard** [comment]
ok, sorry I didn't remember!
